name: Push Nuget Package to GitHub Package Registry

on:
  push:
    branches: [master, develop]
    tags:
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: "Release"
  DOTNET_VERSION: "6.0.x"
  GITHUB_PACKAGE_REGISTRY_URL: https://nuget.pkg.github.com/yuriy-butkevych/index.json
  SUFFIX: ${{ github.ref == 'refs/heads/develop' && '-prerelease' || '' }}

jobs:
  nuget-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate build number
        id: build_number
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          bump_each_commit: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.GITHUB_PACKAGE_REGISTRY_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build Fabillio.Common.Exceptions/Fabillio.Common.Exceptions.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Validation/Fabillio.Common.Validation.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Configurations/Fabillio.Common.Configurations.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Notifications/Fabillio.Common.Notifications.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Helpers/Fabillio.Common.Helpers.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Services/Fabillio.Common.Services.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Clients/Fabillio.Common.Clients.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Messaging/Fabillio.Common.Messaging.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Actors/Fabillio.Common.Actors.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Events.Abstractions/Fabillio.Common.Events.Abstractions.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Events/Fabillio.Common.Events.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet build Fabillio.Common.Tests/Fabillio.Common.Tests.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}

          dotnet pack Fabillio.Common.Exceptions/Fabillio.Common.Exceptions.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Validation/Fabillio.Common.Validation.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Configurations/Fabillio.Common.Configurations.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Notifications/Fabillio.Common.Notifications.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Helpers/Fabillio.Common.Helpers.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Services/Fabillio.Common.Services.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Clients/Fabillio.Common.Clients.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Messaging/Fabillio.Common.Messaging.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Actors/Fabillio.Common.Actors.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Events.Abstractions/Fabillio.Common.Events.Abstractions.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Events/Fabillio.Common.Events.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}
          dotnet pack Fabillio.Common.Tests/Fabillio.Common.Tests.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}${{ env.SUFFIX }}

      - name: nuget publish
        run: dotnet nuget push *.Common.*/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
