name: Build

on:
    pull_request:
        branches: [master, develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v1

            - name: Build
              run: |
                  dotnet restore
                  dotnet build

            - name: Test
              run: dotnet test
